# Group by and Aggregating

#### Group by is going to group together the values in the column and display them all in the same row and it allows in aggregation

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\vidhi\OneDrive\Desktop\coding\Pandas\data\csv.files\Flavors.csv")

In [3]:
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [4]:
group_by_frame = df.groupby('Base Flavor')

In [5]:
group_by_frame

In [6]:
group_by_frame.mean(numeric_only = True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [7]:
# Combining the above groupby and aggregate funtion in one line.
df.groupby('Base Flavor').mean(numeric_only = True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [8]:
df.groupby('Base Flavor').count()

             Flavor  Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate         3      3              3               3             3
Vanilla           6      6              6               6             6

In [9]:
df.groupby('Base Flavor').min()

                  Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate      Chocolate   Yes            8.2             7.0          15.2
Vanilla      Cake Batter    No            2.3             3.4           5.7

In [10]:
df.groupby('Base Flavor').max()
# (In the flavor values are coming according to alphabetical order).

                 Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate    Rocky Road   Yes            8.8             7.6          16.6
Vanilla         Vanilla   Yes           10.0             8.0          18.0

In [11]:
df.groupby('Base Flavor').sum(numeric_only = True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate             25.2            21.7          47.1
Vanilla               34.2            33.9          68.1

In [12]:
# Using a separate aggregate function for all these aggregate calculations(sum,count,mean,etc).
df.groupby('Base Flavor').agg({'Flavor Rating':['max','min','mean','sum','count']})
# What we need to pass in our aggregate function is actually a dictionary.

            Flavor Rating
                      max  min mean   sum count
Base Flavor
Chocolate             8.8  8.2  8.4  25.2     3
Vanilla              10.0  2.3  5.7  34.2     6

In [13]:
df.groupby('Base Flavor').agg({'Flavor Rating':['mean','min','max','sum','count'],'Texture Rating':['mean','min','max','sum','count']})

            Flavor Rating                        Texture Rating            \
                     mean  min   max   sum count           mean  min  max
Base Flavor
Chocolate             8.4  8.2   8.8  25.2     3       7.233333  7.0  7.6
Vanilla               5.7  2.3  10.0  34.2     6       5.650000  3.4  8.0


              sum count
Base Flavor
Chocolate    21.7     3
Vanilla      33.9     6

In [14]:
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [15]:
# We can group on multiple columns
df.groupby(['Base Flavor','Liked']).mean(numeric_only = True)

                   Flavor Rating  Texture Rating  Total Rating
Base Flavor Liked
Chocolate   Yes              8.4        7.233333     15.700000
Vanilla     No               3.6        4.466667      8.066667
            Yes              7.8        6.833333     14.633333

In [16]:
df.groupby(['Base Flavor','Liked']).agg({'Flavor Rating':['mean','max','min','sum','count']})

                  Flavor Rating
                           mean   max  min   sum count
Base Flavor Liked
Chocolate   Yes             8.4   8.8  8.2  25.2     3
Vanilla     No              3.6   4.7  2.3  10.8     3
            Yes             7.8  10.0  6.5  23.4     3

In [17]:
# All these aggregate function can be given by using describe() function which gives a high level overview
df.groupby('Base Flavor').describe()

            Flavor Rating                                             \
                    count mean       std  min    25%  50%  75%   max
Base Flavor
Chocolate             3.0  8.4  0.346410  8.2  8.200  8.2  8.5   8.8
Vanilla               6.0  5.7  2.710719  2.3  4.025  5.6  6.8  10.0

            Texture Rating            ...             Total Rating         \
                     count      mean  ...    75%  max        count   mean
Base Flavor                           ...
Chocolate              3.0  7.233333  ...  7.350  7.6          3.0  15.70
Vanilla                6.0  5.650000  ...  6.375  8.0          6.0  11.35


                  std   min     25%   50%     75%   max
Base Flavor
Chocolate    0.781025  15.2  15.250  15.3  15.950  16.6
Vanilla      4.263684   5.7   9.025  11.1  13.175  18.0

[2 rows x 24 columns]

In [18]:
pd.set_option('display.max.columns',24)