# Merge, Join, and Concatenate

In [1]:
import pandas as pd

In [2]:
# we will be using 2 different dataframes(left and right) which would be used for joining etc.
df1 = pd.read_csv(r"C:\Users\vidhi\OneDrive\Desktop\coding\Pandas\data\csv.files\LOTR.csv")
df1

   FellowshipID FirstName     Skills
0          1001     Frodo     Hiding
1          1002   Samwise  Gardening
2          1003   Gandalf     Spells
3          1004    Pippin  Fireworks

In [3]:
df2 = pd.read_csv(r"C:\Users\vidhi\OneDrive\Desktop\coding\Pandas\data\csv.files\LOTR 2.csv")
df2

   FellowshipID FirstName   Age
0          1001     Frodo    50
1          1002   Samwise    39
2          1006   Legolas  2931
3          1007    Elrond  6520
4          1008  Barromir    51

## Merge

In [4]:
df1.merge(df2)
# it is default(it gives inner join by default).
# df1 becomes left dataframe and df2 becomes right dataframe automatically.

   FellowshipID FirstName     Skills  Age
0          1001     Frodo     Hiding   50
1          1002   Samwise  Gardening   39

In [5]:
df1.merge(df2, how = 'inner') 
# 'how' tells us how do we merge the dataframes

   FellowshipID FirstName     Skills  Age
0          1001     Frodo     Hiding   50
1          1002   Samwise  Gardening   39

In [6]:
df1.merge(df2, how = 'inner', on = 'FellowshipID')
# 'on' tells us on which column would be choosen to compare for merge
# In the current case we took only one column from which we would join df
# So other same common columns are included by providing them suffixes

   FellowshipID FirstName_x     Skills FirstName_y  Age
0          1001       Frodo     Hiding       Frodo   50
1          1002     Samwise  Gardening     Samwise   39

In [7]:
df1.merge(df2, how = 'inner', on = ['FellowshipID','FirstName'])

   FellowshipID FirstName     Skills  Age
0          1001     Frodo     Hiding   50
1          1002   Samwise  Gardening   39

In [8]:
df1.merge(df2, how ='outer')
# the outer provides every field of dataframe whether they match or not.
# It automattically write NaN(Not a Number) which does not have any field.
# Overlapping data will not be duplicated.

   FellowshipID FirstName     Skills     Age
0          1001     Frodo     Hiding    50.0
1          1002   Samwise  Gardening    39.0
2          1003   Gandalf     Spells     NaN
3          1004    Pippin  Fireworks     NaN
4          1006   Legolas        NaN  2931.0
5          1007    Elrond        NaN  6520.0
6          1008  Barromir        NaN    51.0

In [9]:
df1.merge(df2, how = 'left')
# left join pulls everything from the left df and pulls the remaining overlapping data which we can pull from the right df.

   FellowshipID FirstName     Skills   Age
0          1001     Frodo     Hiding  50.0
1          1002   Samwise  Gardening  39.0
2          1003   Gandalf     Spells   NaN
3          1004    Pippin  Fireworks   NaN

In [10]:
df1.merge(df2, how = 'right')
# We are pulling all the data from right df and merging only the overlapping data from the left df.

   FellowshipID FirstName     Skills   Age
0          1001     Frodo     Hiding    50
1          1002   Samwise  Gardening    39
2          1006   Legolas        NaN  2931
3          1007    Elrond        NaN  6520
4          1008  Barromir        NaN    51

In [11]:
df1.merge(df2, how = 'cross')
# it takes each value from the left df and compare each value from the right df

    FellowshipID_x FirstName_x     Skills  FellowshipID_y FirstName_y   Age
0             1001       Frodo     Hiding            1001       Frodo    50
1             1001       Frodo     Hiding            1002     Samwise    39
2             1001       Frodo     Hiding            1006     Legolas  2931
3             1001       Frodo     Hiding            1007      Elrond  6520
4             1001       Frodo     Hiding            1008    Barromir    51
5             1002     Samwise  Gardening            1001       Frodo    50
6             1002     Samwise  Gardening            1002     Samwise    39
7             1002     Samwise  Gardening            1006     Legolas  2931
8             1002     Samwise  Gardening            1007      Elrond  6520
9             1002     Samwise  Gardening            1008    Barromir    51
10            1003     Gandalf     Spells            1001       Frodo    50
11            1003     Gandalf     Spells            1002     Samwise    39
12            1003     Gandalf     Spells            1006     Legolas  2931
13            1003     Gandalf     Spells            1007      Elrond  6520
14            1003     Gandalf     Spells            1008    Barromir    51
15            1004      Pippin  Fireworks            1001       Frodo    50
16            1004      Pippin  Fireworks            1002     Samwise    39
17            1004      Pippin  Fireworks            1006     Legolas  2931
18            1004      Pippin  Fireworks            1007      Elrond  6520
19            1004      Pippin  Fireworks            1008    Barromir    51

## Join

In [12]:
# It does not have so many default functionality as Merge.
df1.join(df2, on = 'FellowshipID', lsuffix = '_left', rsuffix = '_right')
# It does not really make much sense.

,FellowshipID,FellowshipID_left,FirstName_left,Skills,FellowshipID_right,FirstName_right,Age
0,1001,1001,Frodo,Hiding,NaN,NaN,NaN
1,1002,1002,Samwise,Gardening,NaN,NaN,NaN
2,1003,1003,Gandalf,Spells,NaN,NaN,NaN
3,1004,1004,Pippin,Fireworks,NaN,NaN,NaN

In [13]:
df1.join(df2, on = 'FellowshipID' , how = 'outer', lsuffix = '_Left', rsuffix = '_Right')

,FellowshipID,FellowshipID_Left,FirstName_Left,Skills,FellowshipID_Right,FirstName_Right,Age
NaN,0,NaN,NaN,NaN,1001.0,Frodo,50.0
NaN,1,NaN,NaN,NaN,1002.0,Samwise,39.0
NaN,2,NaN,NaN,NaN,1006.0,Legolas,2931.0
NaN,3,NaN,NaN,NaN,1007.0,Elrond,6520.0
NaN,4,NaN,NaN,NaN,1008.0,Barromir,51.0
0.0,1001,1001.0,Frodo,Hiding,NaN,NaN,NaN
1.0,1002,1002.0,Samwise,Gardening,NaN,NaN,NaN
2.0,1003,1003.0,Gandalf,Spells,NaN,NaN,NaN
3.0,1004,1004.0,Pippin,Fireworks,NaN,NaN,NaN

In [14]:
# We are using index to join the df properly and to make some sense.
df3 = df1.set_index('FellowshipID').join(df2.set_index('FellowshipID'), on = 'FellowshipID', lsuffix = '_left', rsuffix = '_right')
df3
# We can use 'how' to define the type of join.

             FirstName_left     Skills FirstName_right   Age
FellowshipID
1001                  Frodo     Hiding           Frodo  50.0
1002                Samwise  Gardening         Samwise  39.0
1003                Gandalf     Spells             NaN   NaN
1004                 Pippin  Fireworks             NaN   NaN

## Concatenate

#### Concatenate means putting one df on top of another df ,instead of putting one df  on side of another.

In [15]:
pd.concat([df1,df2])

   FellowshipID FirstName     Skills     Age
0          1001     Frodo     Hiding     NaN
1          1002   Samwise  Gardening     NaN
2          1003   Gandalf     Spells     NaN
3          1004    Pippin  Fireworks     NaN
0          1001     Frodo        NaN    50.0
1          1002   Samwise        NaN    39.0
2          1006   Legolas        NaN  2931.0
3          1007    Elrond        NaN  6520.0
4          1008  Barromir        NaN    51.0

In [16]:
pd.concat([df1,df2], join = 'inner')

   FellowshipID FirstName
0          1001     Frodo
1          1002   Samwise
2          1003   Gandalf
3          1004    Pippin
0          1001     Frodo
1          1002   Samwise
2          1006   Legolas
3          1007    Elrond
4          1008  Barromir

In [17]:
pd.concat([df1,df2], join = 'outer', axis = 1)

   FellowshipID FirstName     Skills  FellowshipID FirstName   Age
0        1001.0     Frodo     Hiding          1001     Frodo    50
1        1002.0   Samwise  Gardening          1002   Samwise    39
2        1003.0   Gandalf     Spells          1006   Legolas  2931
3        1004.0    Pippin  Fireworks          1007    Elrond  6520
4           NaN       NaN        NaN          1008  Barromir    51